export const images = {
  image: {
    "01d": require("../assets/weather/01d.png"),
    "01n": require("../assets/weather/01n.png"),
    "02d": require("../assets/weather/02d.png"),
    "02n": require("../assets/weather/02n.png"),
    "03d": require("../assets/weather/03d.png"),
    "03n": require("../assets/weather/03n.png"),
    "04d": require("../assets/weather/04d.png"),
    "04n": require("../assets/weather/04n.png"),
    "09d": require("../assets/weather/09d.png"),
    "09n": require("../assets/weather/09n.png"),
    "10d": require("../assets/weather/10d.png"),
    "10n": require("../assets/weather/10n.png"),
    "11d": require("../assets/weather/11d.png"),
    "11n": require("../assets/weather/11n.png"),
    "13d": require("../assets/weather/13d.png"),
    "13n": require("../assets/weather/13n.png"),
    "50d": require("../assets/weather/50d.png"),
    "50n": require("../assets/weather/50n.png"),
  },
};
